/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "panoply.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
panoplyprog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		compte creercompte_1_arg;
		compte seconnecter_1_arg;
		int affichercompte_1_arg;
		abonnement creerabonnement_1_arg;
		int afficherabonnement_1_arg;
		abonnement majunabonnement_1_arg;
		compte affectationabonnement_1_arg;
		collection creercollection_1_arg;
		int affichercollection_1_arg;
		vetement associervetementcollection_1_arg;
		vetement creervetement_1_arg;
		int affichervetement_1_arg;
		location louervetement_1_arg;
		int afficherlocation_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case CREERCOMPTE:
		_xdr_argument = (xdrproc_t) xdr_compte;
		_xdr_result = (xdrproc_t) xdr_boolean;
		local = (char *(*)(char *, struct svc_req *)) creercompte_1_svc;
		break;

	case SECONNECTER:
		_xdr_argument = (xdrproc_t) xdr_compte;
		_xdr_result = (xdrproc_t) xdr_boolean;
		local = (char *(*)(char *, struct svc_req *)) seconnecter_1_svc;
		break;

	case AFFICHERCOMPTE:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_compte;
		local = (char *(*)(char *, struct svc_req *)) affichercompte_1_svc;
		break;

	case NOMBRECOMPTE:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) nombrecompte_1_svc;
		break;

	case CREERABONNEMENT:
		_xdr_argument = (xdrproc_t) xdr_abonnement;
		_xdr_result = (xdrproc_t) xdr_boolean;
		local = (char *(*)(char *, struct svc_req *)) creerabonnement_1_svc;
		break;

	case NOMBREABONNEMENT:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) nombreabonnement_1_svc;
		break;

	case AFFICHERABONNEMENT:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_abonnement;
		local = (char *(*)(char *, struct svc_req *)) afficherabonnement_1_svc;
		break;

	case MAJUNABONNEMENT:
		_xdr_argument = (xdrproc_t) xdr_abonnement;
		_xdr_result = (xdrproc_t) xdr_boolean;
		local = (char *(*)(char *, struct svc_req *)) majunabonnement_1_svc;
		break;

	case AFFECTATIONABONNEMENT:
		_xdr_argument = (xdrproc_t) xdr_compte;
		_xdr_result = (xdrproc_t) xdr_boolean;
		local = (char *(*)(char *, struct svc_req *)) affectationabonnement_1_svc;
		break;

	case CREERCOLLECTION:
		_xdr_argument = (xdrproc_t) xdr_collection;
		_xdr_result = (xdrproc_t) xdr_boolean;
		local = (char *(*)(char *, struct svc_req *)) creercollection_1_svc;
		break;

	case NOMBRECOLLECTION:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) nombrecollection_1_svc;
		break;

	case AFFICHERCOLLECTION:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_collection;
		local = (char *(*)(char *, struct svc_req *)) affichercollection_1_svc;
		break;

	case ASSOCIERVETEMENTCOLLECTION:
		_xdr_argument = (xdrproc_t) xdr_vetement;
		_xdr_result = (xdrproc_t) xdr_boolean;
		local = (char *(*)(char *, struct svc_req *)) associervetementcollection_1_svc;
		break;

	case CREERVETEMENT:
		_xdr_argument = (xdrproc_t) xdr_vetement;
		_xdr_result = (xdrproc_t) xdr_boolean;
		local = (char *(*)(char *, struct svc_req *)) creervetement_1_svc;
		break;

	case AFFICHERVETEMENT:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_vetement;
		local = (char *(*)(char *, struct svc_req *)) affichervetement_1_svc;
		break;

	case NOMBREVETEMENT:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) nombrevetement_1_svc;
		break;

	case LOUERVETEMENT:
		_xdr_argument = (xdrproc_t) xdr_location;
		_xdr_result = (xdrproc_t) xdr_boolean;
		local = (char *(*)(char *, struct svc_req *)) louervetement_1_svc;
		break;

	case NOMBRELOCATION:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) nombrelocation_1_svc;
		break;

	case AFFICHERLOCATION:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_location;
		local = (char *(*)(char *, struct svc_req *)) afficherlocation_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (PANOPLYPROG, PANOPLYVERS);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, PANOPLYPROG, PANOPLYVERS, panoplyprog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (PANOPLYPROG, PANOPLYVERS, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, PANOPLYPROG, PANOPLYVERS, panoplyprog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (PANOPLYPROG, PANOPLYVERS, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
